services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: focusforge-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - focusforge-net

networks:
  focusforge-net:
    name: focusforge-net
    driver: bridge
